default_language_version:
  python: python3.9
default_stages: [commit, manual]
files: advent21/
exclude: ^inputs/

variables:
  exclude_regex: &regex
    inputs/


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
        exclude: (^.*\.md$|inputs/)
      - id: end-of-file-fixer
        exclude: *regex
      - id: debug-statements
      - id: check-yaml
        args: [--allow-multiple-documents]

  - repo: https://github.com/ambv/black
    rev: 21.5b2
    hooks:
      - id: black
        args: [--line-length=88]
        types: [python]
        exclude: *regex

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        # E255 is broken with / in function definitions
        args: [--max-line-length=88, --max-complexity=10, "--ignore=E203,E225,W503"]
        exclude: *regex

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [--errors-only]
        exclude: *regex

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        args: [--line-width=88, --multi-line=3, --project=kw, --section-default=THIRDPARTY, --trailing-comma]
        exclude: *regex

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        exclude: *regex
